"""add FB columns for user

Revision ID: 430949df34aa
Revises: 6749f0f42879
Create Date: 2023-03-28 23:21:26.797572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430949df34aa'
down_revision = '6749f0f42879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('FBuserID', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('FBaccessToken', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_FBuserID'), 'user', ['FBuserID'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_FBuserID'), table_name='user')
    op.drop_column('user', 'FBaccessToken')
    op.drop_column('user', 'FBuserID')
    # ### end Alembic commands ###
