"""add is_edited for tweet

Revision ID: 6749f0f42879
Revises: 4783fc4800b4
Create Date: 2023-03-22 22:07:33.793136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6749f0f42879'
down_revision = '4783fc4800b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('is_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'is_edited')
    # ### end Alembic commands ###
