"""add FBpicture for user

Revision ID: e95432870cb4
Revises: 430949df34aa
Create Date: 2023-03-29 22:44:43.749833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95432870cb4'
down_revision = '430949df34aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('FBpicture', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'FBpicture')
    # ### end Alembic commands ###
